# Generated by Django 5.0.6 on 2024-06-23 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageUpload',
            new_name='UrineStrip',
        ),
    ]
